// variables used for action types

export const ADD_TIMER_STATE_SUCCESS = 'ADD_TIMER_STATE_SUCCESS'
export const ADD_TIMER_STATE_FAIL = 'ADD_TIMER_STATE_FAIL'

export const LIST_HISTORY_REQUEST = 'LIST_HISTORY_REQUEST'
export const LIST_HISTORY_SUCCESS = 'LIST_HISTORY_SUCCESS'
export const LIST_HISTORY_FAIL = 'LIST_HISTORY_FAIL'